### PR TITLE
Turn on recheck headers

### PR DESCRIPTION
**Pull request by paytonrules**
Seems too easy, I probably flubbed it.

### CODE REVIEW

**Review by rmulhol — COMMENTED** [review]
I _think_ this should do it 👍 

Prob worth doing the same thing for other plugins - maybe even starting there

**Comment by paytonrules** [comment]
That's a good point - want to do Oasis first? https://github.com/makerdao/vdb-oasis-transformers/pull/12

**Comment by rmulhol** [comment]
Would like to do this in a separate container so it doesn't slow down the main sync

**Comment by ecmendenhall** [comment]
We're gonna run this as a parallel container.

**Pull request closed without merging**
